import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{Crown,MapPin,CalendarDays,ArrowRight,Check,Users,Building2,PartyPopper,Menu,X}from'lucide-react';import'./style.css';
const countries=['Taiwan','Japan','Korea','Thailand','Philippines','Vietnam','Singapore','Malaysia','Indonesia','India','Australia','New Zealand','USA','Canada','Mexico','Brazil','Argentina','France','Italy','Spain','Portugal','Germany','UK','Netherlands','Sweden','Poland','Ukraine','Turkey','UAE','South Africa','Egypt','Morocco','Mongolia','Kazakhstan','Hong Kong','Macau','China','Cambodia','Myanmar','Nepal'];
const tiers=[['VIP 1','70,000','最高規格國家桌席次＋OPERA 慶功宴'],['VIP 2','60,000','國家桌席次＋OPERA 慶功宴'],['VIP 3','40,000','國家桌贊助席次']];
function App(){const[nav,setNav]=useState(false),[country,setCountry]=useState(''),[tier,setTier]=useState('VIP 1'),[member,setMember]=useState(1),[modal,setModal]=useState(null);const status=useMemo(()=>Object.fromEntries(countries.map((c,i)=>[c,i<3?'Sponsored':i<6?'Reserved':'Available'])),[]);
const go=id=>{document.getElementById(id)?.scrollIntoView({behavior:'smooth'});setNav(false)};
return <><header><button className="brand" onClick={()=>go('top')}><span className="crest"><Crown size={18}/></span><span>FOBI <small>2026</small></span></button><nav className={nav?'open':''}><button onClick={()=>go('countries')}>認領國家</button><button onClick={()=>go('member')}>會員贊助</button><button onClick={()=>go('event')}>活動資訊</button></nav><button className="hamb" onClick={()=>setNav(!nav)}>{nav?<X/>:<Menu/>}</button></header>
<main id="top"><section className="hero"><div className="glow"/><div className="heroCopy"><p className="eyebrow">TAIPEI · 30 OCTOBER 2026</p><h1>FACE OF BEAUTY<br/><i>INTERNATIONAL</i></h1><p className="zh">世界美顏小姐選美總決賽</p><p className="manifesto">40 COUNTRIES <b>·</b> ONE NIGHT <b>·</b> TAIPEI</p><div className="heroActions"><button className="gold" onClick={()=>go('countries')}><Building2/> 認領一個國家 <ArrowRight/></button><button className="glass" onClick={()=>go('member')}><Users/> 會員贊助 NT$3,000</button></div></div><div className="silhouette"><div className="crown">♛</div><div className="figure"/></div></section>
<section className="facts" id="event"><div><CalendarDays/><span><b>2026.10.30</b> 星期五</span></div><div><MapPin/><span><b>臺北茹曦酒店 2F</b> Taipei</span></div><div><Crown/><span><b>14:00 總決賽</b> 19:00 頒獎晚宴</span></div><div><PartyPopper/><span><b>OPERA</b> After Party</span></div></section>
<section className="intro"><p className="eyebrow">THE COUNTRY TABLE EXPERIENCE</p><h2>一桌，代表一個國家。</h2><p>40 國佳麗齊聚台北。企業可認領專屬國家桌，讓品牌與佳麗、國際賓客及總決賽現場共同留下年度影像。</p></section>
<section id="countries" className="countries"><div className="sectionHead"><div><p className="eyebrow">SPONSOR A COUNTRY</p><h2>選擇你的國家桌</h2></div><p>綠點可認領 · 金色已保留／贊助</p></div><div className="countryGrid">{countries.map((c,i)=><button key={c} className={'country '+status[c].toLowerCase()} disabled={status[c]!=='Available'} onClick={()=>{setCountry(c);setModal('sponsor')}}><span className="num">{String(i+1).padStart(2,'0')}</span><strong>{c}</strong><small>{status[c]}</small></button>)}</div><p className="note">示範狀態將由正式後台即時庫存取代；付款前需再次確認桌位。</p></section>
<section className="tiers"><p className="eyebrow">TABLE SPONSORSHIP</p><h2>企業認桌方案</h2><div className="tierGrid">{tiers.map(t=><article key={t[0]}><span>{t[0]}</span><h3>NT$ {t[1]}</h3><p>{t[2]}</p><button onClick={()=>{setTier(t[0]);setModal('sponsor')}}>選擇此方案 <ArrowRight/></button></article>)}</div></section>
<section id="member" className="member"><div><p className="eyebrow">SELF MEMBER EXPERIENCE</p><h2>不只是入場，<br/>成為這一夜的贊助會員。</h2><p>SELF 會員以每位 NT$3,000 參與總決賽國際晚宴，並包含 OPERA 慶功宴資格。</p><ul><li><Check/>總決賽國際晚宴</li><li><Check/>頒獎典禮</li><li><Check/>OPERA After Party</li><li><Check/>電子 QR 入場憑證（正式串接後啟用）</li></ul></div><div className="ticket"><small>MEMBER SPONSORSHIP</small><strong>NT$ 3,000</strong><span>/ PERSON</span><label>人數 <div><button onClick={()=>setMember(Math.max(1,member-1))}>−</button><b>{member}</b><button onClick={()=>setMember(member+1)}>＋</button></div></label><p>合計 NT$ {(member*3000).toLocaleString()}</p><button className="gold" onClick={()=>setModal('member')}>我要贊助入席 <ArrowRight/></button></div></section>
<section className="closing"><Crown/><p>FACE OF BEAUTY INTERNATIONAL</p><h2>Be part of the world<br/>that arrives in Taipei.</h2><button className="gold" onClick={()=>go('countries')}>立即認領國家桌</button></section></main>
<footer><b>FOBI 2026</b><span>Face of Beauty International · Taipei</span><small>© 2026 FOBI. All rights reserved.</small></footer>
{modal&&<div className="modalBack" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button>{modal==='sponsor'?<><p className="eyebrow">SPONSOR APPLICATION</p><h2>企業認桌</h2><p>{country?<>國家：<b>{country}</b><br/></>:null}方案：<b>{tier}</b></p><label>公司／品牌<input placeholder="品牌名稱"/></label><label>聯絡人<input placeholder="姓名"/></label><label>手機<input placeholder="09xx xxx xxx"/></label><label>Email<input type="email" placeholder="name@company.com"/></label><button className="gold" onClick={()=>alert('目前為預售申請介面。正式金流與 CRM API 接妥後才會送出訂單。')}>送出贊助意向 <ArrowRight/></button><small>目前不會扣款。正式上線前將串接 ECPay、SELF ID 與桌位鎖定。</small></>:<><p className="eyebrow">SELF MEMBER</p><h2>會員贊助入席</h2><p>{member} 位 · <b>NT$ {(member*3000).toLocaleString()}</b></p><label>姓名<input placeholder="會員姓名"/></label><label>手機<input placeholder="09xx xxx xxx"/></label><label>Email<input type="email" placeholder="SELF ID / Email"/></label><button className="gold" onClick={()=>alert('目前為預售介面，尚未啟用正式扣款與 QR 發票。')}>確認贊助資料 <ArrowRight/></button><small>正式付款與 QR 電子票將於 ECPay / SELF ID API 串接後啟用。</small></>}</div></div>}</>}
createRoot(document.getElementById('root')).render(<App/>);